//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lplfw.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductClass> ProductClassSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<MaterialClass> MaterialClassSet { get; set; }
        public virtual DbSet<Material> MaterialSet { get; set; }
        public virtual DbSet<RecipeItem> RecipeItemSet { get; set; }
        public virtual DbSet<Privilege> PrivilegeSet { get; set; }
        public virtual DbSet<UserGroup> UserGroupSet { get; set; }
        public virtual DbSet<UserGroupPrivilegeItem> UserGroupPrivilegeItemSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Supplier> SupplierSet { get; set; }
        public virtual DbSet<Storage> StorageSet { get; set; }
        public virtual DbSet<ProductStock> ProductStockSet { get; set; }
        public virtual DbSet<MaterialStock> MaterialStockSet { get; set; }
        public virtual DbSet<StockIn> StockInSet { get; set; }
        public virtual DbSet<StockOut> StockOutSet { get; set; }
        public virtual DbSet<ProductStockInItem> ProductStockInItemSet { get; set; }
        public virtual DbSet<MaterialStockInItem> MaterialStockInItemSet { get; set; }
        public virtual DbSet<ProductStockOutItem> ProductStockOutItemSet { get; set; }
        public virtual DbSet<MaterialStockOutItem> MaterialStockOutItemSet { get; set; }
        public virtual DbSet<Sales> SalesSet { get; set; }
        public virtual DbSet<SalesItem> SalesItemSet { get; set; }
        public virtual DbSet<Purchase> PurchaseSet { get; set; }
        public virtual DbSet<PurchaseItem> PurchaseItemSet { get; set; }
        public virtual DbSet<MaterialPrice> MaterialPriceSet { get; set; }
        public virtual DbSet<AssemblyLine> AssemblyLineSet { get; set; }
        public virtual DbSet<Requisition> RequisitionSet { get; set; }
        public virtual DbSet<RequisitionItem> RequisitionItemSet { get; set; }
        public virtual DbSet<Return> ReturnSet { get; set; }
        public virtual DbSet<ReturnItem> ReturnItemSet { get; set; }
        public virtual DbSet<Production> ProductionSet { get; set; }
        public virtual DbSet<ProductionQuality> ProductionQualitySet { get; set; }
        public virtual DbSet<Log> LogSet { get; set; }
    }
}
