
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lplfw.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Purchase()
    {

        this.Items = new HashSet<PurchaseItem>();

    }


    public int Id { get; set; }

    public string Status { get; set; }

    public string Priority { get; set; }

    public System.DateTime CreateAt { get; set; }

    public System.DateTime FinishedAt { get; set; }

    public string Description { get; set; }

    public int UserId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PurchaseItem> Items { get; set; }

}

}
